Update 2025.02

diff --git a/bin/ca_get_issuer_cert b/bin/ca_get_issuer_cert
--- a/bin/ca_get_issuer_cert
+++ b/bin/ca_get_issuer_cert
@@ -3,7 +3,7 @@
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]
 then
 	echo
-        echo -e "\e[1;33;1mQUICK CA (2024.09)\e[0m -- [ ca_get_issuer_cert ]"
+        echo -e "\e[1;33;1mQUICK CA (2025.02)\e[0m -- [ ca_get_issuer_cert ]"
         echo
         echo "This utility copies Issuing CA certificate to your present location."
         echo
@@ -13,6 +13,14 @@ then
         echo "ca_get_issuer_cert"
         echo
         exit 0
+fi
+
+if [ -z $ISSUING_CA_PATH ] || [ -z $ISSUING_CA_NAME ]
+then
+        echo "ISSUING_CA_* environment variable not found."
+        echo "Please execute 'source $HOME/CA/setenv.sh'"
+        echo
+        exit 1
 fi
 
 cp $ISSUING_CA_PATH/cert/$ISSUING_CA_NAME.cer .
diff --git a/bin/ca_get_root_cert b/bin/ca_get_root_cert
--- a/bin/ca_get_root_cert
+++ b/bin/ca_get_root_cert
@@ -3,7 +3,7 @@
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]
 then
         echo
-        echo -e "\e[1;33;1mQUICK CA (2024.09)\e[0m -- [ ca_get_root_cert ]"
+        echo -e "\e[1;33;1mQUICK CA (2025.02)\e[0m -- [ ca_get_root_cert ]"
         echo
         echo "This utility copies Root CA certificate to your present location."
         echo
@@ -14,6 +14,13 @@ then
         echo
         exit 0
 fi
+
+if [ -z $ROOT_CA_PATH ] || [ -z $ROOT_CA_NAME ]
+then
+        echo "ROOT_CA_* environment variable not found. Please execute 'source "$HOME/CA/setenv.sh"'"
+        exit 1
+fi
+
 
 cp $ROOT_CA_PATH/cert/$ROOT_CA_NAME.cer .
 
